# required-checks.yaml v2
# Location: .github/required-checks.yaml
# Upgraded: OMN-2228 (Phase 5 CI Consolidation)
#
# The `gates` list is the ONLY operational contract for branch protection.
# The `checks` list is documentation only -- it has NO operational effect.
# See: CI_CD_STANDARDS.md (Invariant 2: Single Source of Truth)

schema_version: 2
classification: toolchain

# =============================================================================
# GATES: API-stable check names for branch protection
# These are the ONLY check names that branch protection should require.
# Do NOT rename without following the Branch Protection Migration Safety
# procedure in CI_CD_STANDARDS.md.
# =============================================================================
gates:
  - name: "Quality Gate"
    workflow: ci.yml
    rationale: >
      Aggregates all Tier A code quality checks: lint, mypy, pyright,
      exports validation, enum governance, Kafka import guard,
      migration freeze, architecture handshake, ONEX compliance.

  - name: "Tests Gate"
    workflow: ci.yml
    rationale: >
      Aggregates all test execution: 5-split test matrix, hooks system tests,
      agent framework tests, database schema validation.

  - name: "Security Gate"
    workflow: ci.yml
    rationale: >
      Aggregates security scanning: Bandit SAST and secret detection.

# =============================================================================
# CHECKS: Documentary listing (NO operational effect)
# Branch protection MUST NOT reference check names from this section.
# =============================================================================
checks:
  # Tier A-Org (universal)
  - name: "Code Quality"
    tier: A-Org
    workflow: ci.yml
    gate: "Quality Gate"
    rationale: "ruff format + ruff check + mypy"

  - name: "Python Security Scan"
    tier: A-Org
    workflow: ci.yml
    gate: "Security Gate"
    rationale: "Bandit SAST (medium+ severity)"

  - name: "Secret Detection"
    tier: A-Org
    workflow: ci.yml
    gate: "Security Gate"
    rationale: "detect-secrets scan for leaked credentials"

  # Tier A-Runtime (per-technology)
  - name: "Pyright Type Checking"
    tier: A-Runtime
    workflow: ci.yml
    gate: "Quality Gate"
    rationale: "Pyright strict type checking on src/omniclaude/"

  - name: "Exports Validation"
    tier: A-Runtime
    workflow: ci.yml
    gate: "Quality Gate"
    rationale: "__all__ exports reference real symbols"

  - name: "Enum Governance"
    tier: A-Runtime
    workflow: ci.yml
    gate: "Quality Gate"
    rationale: "ONEX enum naming conventions (UPPER_SNAKE_CASE)"

  - name: "Kafka Import Guard"
    tier: A-Runtime
    workflow: ci.yml
    gate: "Quality Gate"
    rationale: "ARCH-002: no direct Kafka imports in nodes/handlers"

  - name: "Migration Freeze"
    tier: A-Runtime
    workflow: ci.yml
    gate: "Quality Gate"
    rationale: "Blocks new migrations during DB-SPLIT (OMN-2055)"

  - name: "ONEX Compliance"
    tier: A-Runtime
    workflow: ci.yml
    gate: "Quality Gate"
    rationale: "ONEX architecture naming, contracts, method signatures"

  - name: "Architecture Handshake"
    tier: A-Runtime
    workflow: ci.yml
    gate: "Quality Gate"
    rationale: "Cross-repo architecture handshake is current (skips fork PRs)"

  - name: "Tests (Split N/5)"
    tier: A-Runtime
    workflow: ci.yml
    gate: "Tests Gate"
    rationale: "5-split test matrix -- use Tests Gate aggregator instead"

  - name: "Hooks System Tests"
    tier: A-Runtime
    workflow: ci.yml
    gate: "Tests Gate"
    rationale: "Hook scripts and handler modules"

  - name: "Agent Framework Tests"
    tier: A-Runtime
    workflow: ci.yml
    gate: "Tests Gate"
    rationale: "Agent YAML loading and framework validation"

  - name: "Database Schema Validation"
    tier: A-Runtime
    workflow: ci.yml
    gate: "Tests Gate"
    rationale: "DB schema consistency checks"

  # Tier C (profile / informational)
  - name: "Merge Test Coverage"
    tier: C
    workflow: ci.yml
    gate: null
    rationale: "Coverage reporting -- not a correctness check"

  - name: "Build Docker Image"
    tier: C
    workflow: ci.yml
    gate: null
    rationale: "Downstream of all gates -- redundant if gates pass"

# =============================================================================
# EXCLUDED (not in any gate, documented for audit trail)
# =============================================================================
excluded:
  - name: "Performance Benchmarks"
    reason: "Removed from CI -- informational metrics should not block merges"

  - name: "Docker Compose Stack Validation"
    reason: "Removed from CI -- infrastructure validation, not code correctness"

  - name: "Integration Tests"
    reason: "Separate workflow (integration-tests.yml) -- requires remote services, runs on main/develop only"

  - name: "Code Quality (Strict Mode)"
    reason: "Eliminated -- redundant with Code Quality from consolidated workflow"

  - name: "Enhanced Unit Tests Gate"
    reason: "Eliminated -- consolidated into Tests Gate"

  - name: "CI Tests Gate"
    reason: "Eliminated -- consolidated into Tests Gate"
