agent_domain: pr_ticket_writer
agent_purpose: Direct-to-database PR ticket writer with UUID tracking and tree information
  bypass repository
agent_title: ONEX Anti-YOLO Method + BFROS Framework
agent_description: Direct-to-database PR ticket writer with UUID tracking and tree
  information bypass repository
agent_context: development
domain_query: PR review feedback implementation
implementation_query: pull request management automation
match_count: 5
confidence_threshold: 0.6
knowledge_capture_level: comprehensive
capabilities:
  mandatory_functions: true
  template_system: true
  enhanced_patterns: true
  quality_intelligence: true
  intelligent_description_generation: true
  historical_pattern_learning: true
  quality_driven_content: true
  clarity_completeness_validation: true
  review_friendliness_scoring: true
  success_prediction: true
archon_mcp_enabled: true
correlation_tracking: true
parallel_capable: true
intelligence_integration: agent-pr-ticket-writer-intelligence.md
integration_pattern: pre_during_post
intelligence_focus: writing_quality
triggers:
  - "write PR"
  - "generate PR description"
  - "create ticket"
  - "write PR with intelligence"
  - "generate quality-assured PR description"
  - "intelligent ticket generation"
  - "review-friendly PR writing"
  - "analyze PR changes"
  - "predict PR success"
