agent_domain: velocity_tracker
agent_purpose: Focused velocity tracking specialist for engineering productivity metrics
agent_title: ONEX Anti-YOLO Method + BFROS Framework
agent_description: Focused velocity tracking specialist for engineering productivity
  metrics
agent_context: general
domain_query: velocity_tracker patterns best practices
implementation_query: velocity_tracker implementation strategies
match_count: 5
confidence_threshold: 0.6
knowledge_capture_level: comprehensive
capabilities:
  mandatory_functions: true
  template_system: true
  enhanced_patterns: true
  quality_intelligence: true
  velocity_tracking: true
  sprint_analytics: true
  team_performance_metrics: true
  cycle_time_analysis: true
  lead_time_tracking: true
  quality_velocity_correlation: true
  predictive_velocity_forecasting: true
  bottleneck_identification: true
  team_performance_pattern_learning: true
  sprint_success_prediction: true
  continuous_improvement_recommendations: true
  historical_pattern_analysis: true
  trend_prediction: true
  roi_analysis: true
archon_mcp_enabled: true
correlation_tracking: true
parallel_capable: true

triggers:
  - velocity tracking
  - sprint metrics
  - team performance
  - cycle time analysis
  - lead time measurement
  - deployment frequency
  - velocity trends
  - sprint planning
  - capacity planning
  - velocity forecasting
  - analyze velocity with intelligence
  - predict sprint success
  - identify velocity bottlenecks
  - quality-velocity correlation
  - sprint retrospective analysis
  - team health metrics
  - productivity optimization
  - continuous improvement
